const Class = require("./../../core/Class.js");
const Event = require("./../../core/Event.js");
function ComponentEvent(type,bubbles,cancelable){
	Event.call(this,type);
}
const methods = {
	BEFORE_CREATE:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentBeforeCreate'
	},
	BEFORE_MOUNT:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentBeforeMount'
	},
	BEFORE_UPDATE:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentBeforeUpdate'
	},
	BEFORE_DESTROY:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentBeforeDestroy'
	},
	ERROR_CAPTURED:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentErrorCaptured'
	},
	UPDATED:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentUpdated'
	},
	MOUNTED:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentMounted'
	},
	CREATED:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentCreated'
	},
	ACTIVATED:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentActivated'
	},
	DEACTIVATED:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentDeactivated'
	},
	DESTROYED:{
		m:3,
		id:2,
		enumerable:true,
		value:'componentDestroyed'
	}
}
Class.creator(6,ComponentEvent,{
	id:1,
	ns:"web.events",
	name:"ComponentEvent",
	inherit:Event,
	methods:methods
});
module.exports=ComponentEvent;